<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_First Name is required</name>
   <tag></tag>
   <elementGuidId>f99dddf5-0c43-4631-98ad-9f92909eb1ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-mdc-error-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-error-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;First Name is required&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>816b40fc-11f4-42de-b083-34ffc1a19341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5600171a-0fc7-4d7a-ac92-7e72566e5310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-error mat-mdc-form-field-bottom-align ng-tns-c508571215-3 ng-star-inserted</value>
      <webElementGuid>2b50867d-6c44-4038-81c0-7bc503754ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>553dc937-4173-45bd-ba43-4e72f122b4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-error-0</value>
      <webElementGuid>839db8da-2325-43bd-b0f9-b638e2719d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Name is required</value>
      <webElementGuid>47aa8af2-f76a-40dd-b6de-0c1627d1d751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-error-0&quot;)</value>
      <webElementGuid>d2dcce66-fb03-4569-ae1e-fc0b1e0aa334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-mdc-error-0']</value>
      <webElementGuid>7b7401ea-9f81-42e2-81ec-4224b7aba0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name'])[1]/following::mat-error[1]</value>
      <webElementGuid>a4092b15-9523-4b69-a956-ac1bed442837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::mat-error[1]</value>
      <webElementGuid>a161eb62-dc5f-43d2-9566-2c2a417c437a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>e4165c7e-fc5c-4a01-868d-2a81b11061e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>241740d3-b4e4-4f94-9bd9-08b9c1d75820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First Name is required']/parent::*</value>
      <webElementGuid>7f4eb116-ad0a-4160-875e-44b485bb07cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>317c219f-469c-4097-bf2a-534433d8ca66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-mdc-error-0' and (text() = 'First Name is required' or . = 'First Name is required')]</value>
      <webElementGuid>1b17af50-887e-4711-820c-3794e679f3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
