<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_User Name is required</name>
   <tag></tag>
   <elementGuidId>20d39569-4db9-4905-83c9-ba4a553a0530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-mdc-error-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-error-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;User Name is required&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>3d721929-59f5-42c2-afb4-47acf14a0bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2439465a-fe0d-4e05-879e-037b88c66161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-error mat-mdc-form-field-bottom-align ng-tns-c508571215-5 ng-star-inserted</value>
      <webElementGuid>25280f30-7f91-42be-9cf4-bac2b95b1d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>86e70cf0-92cb-4310-9335-f8f5c78c4bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-error-2</value>
      <webElementGuid>ae9f7490-fcd8-478d-9f1a-d0b46eef73d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name is required </value>
      <webElementGuid>d550f994-125c-4fa8-a889-6c63020cb869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-error-2&quot;)</value>
      <webElementGuid>e0765b35-a771-42b4-82ae-0b9b6c81af86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-mdc-error-2']</value>
      <webElementGuid>7028e2c2-4473-4165-8eea-af8611b838f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/following::mat-error[1]</value>
      <webElementGuid>e0a8032f-e2be-4ef5-85b1-1828c0099193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Name is required'])[1]/following::mat-error[1]</value>
      <webElementGuid>1c095d20-db85-432a-9344-e81a151e5f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>f1556e6a-8ece-4b2e-ac18-57a9f861c43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>73e834e7-e4e7-4ea0-b8c9-f6047f2a6ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name is required']/parent::*</value>
      <webElementGuid>5c99abf5-29e9-40a1-9955-8657bdd5df4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div[2]/div/mat-error</value>
      <webElementGuid>720749d2-c6b6-4f67-821d-d2e19b0ab6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-mdc-error-2' and (text() = 'User Name is required ' or . = 'User Name is required ')]</value>
      <webElementGuid>f0550bae-6186-4dc2-90f0-316101898909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
